-- Recruit.com.hk — AI Features Migration
-- Migration: 0002_ai_tables
-- Description: Add job alerts, chatbot sessions, chatbot messages, and AI embedding cache

-- ─── Job Alerts ───────────────────────────────────────────────────────────────
-- Candidates set up alerts to be notified of matching jobs

CREATE TABLE IF NOT EXISTS job_alerts (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  candidate_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name              TEXT    NOT NULL DEFAULT 'My Alert',
  keywords          TEXT,   -- comma-separated keywords
  category          TEXT,
  location          TEXT,
  employment_type   TEXT,
  salary_min        INTEGER,
  use_ai_matching   INTEGER NOT NULL DEFAULT 0, -- 1 = AI semantic, 0 = keyword filter
  is_active         INTEGER NOT NULL DEFAULT 1,
  last_triggered_at TEXT,
  created_at        TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_job_alerts_candidate ON job_alerts(candidate_id);
CREATE INDEX IF NOT EXISTS idx_job_alerts_active    ON job_alerts(is_active);

-- ─── AI Embeddings Cache ──────────────────────────────────────────────────────
-- Stores OpenAI text-embedding-3-small vectors (1536 dims) as JSON text for jobs
-- and candidate profiles. Used for semantic job matching.

CREATE TABLE IF NOT EXISTS ai_embeddings (
  entity_type TEXT    NOT NULL, -- 'job' | 'candidate'
  entity_id   INTEGER NOT NULL,
  embedding   TEXT    NOT NULL, -- JSON array of 1536 floats
  model       TEXT    NOT NULL DEFAULT 'text-embedding-3-small',
  created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (entity_type, entity_id)
);

-- ─── Chatbot Sessions ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS chatbot_sessions (
  id            TEXT    PRIMARY KEY, -- UUID generated by worker
  user_id       INTEGER REFERENCES users(id) ON DELETE SET NULL, -- NULL = anonymous
  user_type     TEXT    NOT NULL DEFAULT 'anonymous', -- 'candidate' | 'employer' | 'anonymous'
  created_at    TEXT    NOT NULL DEFAULT (datetime('now')),
  last_active   TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_chatbot_sessions_user ON chatbot_sessions(user_id);

-- ─── Chatbot Messages ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS chatbot_messages (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id  TEXT    NOT NULL REFERENCES chatbot_sessions(id) ON DELETE CASCADE,
  role        TEXT    NOT NULL CHECK(role IN ('user', 'assistant', 'system')),
  content     TEXT    NOT NULL,
  intent      TEXT,   -- classified intent: 'job_search' | 'app_status' | 'career_advice' | 'general'
  tokens_used INTEGER,
  created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_chatbot_messages_session ON chatbot_messages(session_id);

-- ─── CV Parsed Data ───────────────────────────────────────────────────────────
-- Stores AI-extracted structured data from uploaded CV text

CREATE TABLE IF NOT EXISTS cv_parsed_data (
  candidate_id  INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  raw_text      TEXT,                -- full text extracted from CV
  parsed_json   TEXT,                -- JSON: { skills, experience, education, languages }
  parsed_at     TEXT    NOT NULL DEFAULT (datetime('now'))
);
